# Generated by Django 4.0.4 on 2022-06-07 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'ordering': ['-time_created'], 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
        migrations.AddField(
            model_name='active',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='active',
            name='av_pulse',
            field=models.IntegerField(blank=True, verbose_name='Средний пульс'),
        ),
        migrations.AlterField(
            model_name='active',
            name='max_pulse',
            field=models.IntegerField(blank=True, verbose_name='Максимальный пульс'),
        ),
        migrations.AlterField(
            model_name='active',
            name='min_pulse',
            field=models.IntegerField(blank=True, verbose_name='Минимальный пульс'),
        ),
    ]
