# Generated by Django 4.0.4 on 2022-05-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
        migrations.AlterField(
            model_name='active',
            name='av_pulse',
            field=models.IntegerField(blank=True, verbose_name='Средний пульс'),
        ),
        migrations.AlterField(
            model_name='active',
            name='max_pulse',
            field=models.IntegerField(blank=True, verbose_name='Максимальный пульс'),
        ),
        migrations.AlterField(
            model_name='active',
            name='min_pulse',
            field=models.IntegerField(blank=True, verbose_name='Минимальный пульс'),
        ),
    ]
