# Generated by Django 4.0.4 on 2022-06-06 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('active', '0002_alter_active_options_alter_active_av_pulse_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'ordering': ['-time_created'], 'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
        migrations.AddField(
            model_name='active',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
