# Generated by Django 4.0.4 on 2022-06-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('active', '0003_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active',
            old_name='user',
            new_name='auth',
        ),
    ]
