# Generated by Django 4.0.4 on 2022-05-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_main_options_alter_main_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Active',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
